version: '3.4'

services:
  messageBroker:
    image: rabbitmq:3-management
    container_name: messageBroker
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - main

networks:
  main:
    name: nodesj-services-demo-network
